### PR TITLE
fixed decodegroup tuple variable type starting index

### PR DESCRIPTION
**Pull request by tatt5749**

### CODE REVIEW

**Comment by tatt5749** [comment]
fix tuple variable type decode

**Comment by drlecks** [comment]
Can you share data structure or contract example to replicate the issue?

**Comment by tatt5749** [comment]
$outputs = [
  0 => {#1325
    +"components": array:3 [
      0 => {#1322
        +"internalType": "uint256"
        +"name": "buybackAmount"
        +"type": "uint256"
      }
      1 => {#1323
        +"internalType": "uint256"
        +"name": "interestAmount"
        +"type": "uint256"
      }
      2 => {#1324
        +"internalType": "uint256"
        +"name": "redeemableAmount"
        +"type": "uint256"
      }
    ]
    +"internalType": "struct TestTokenStaking.RedeemInfo"
    +"name": ""
    +"type": "tuple"
  }
]

$encoded = "000000000000000000000000000000000000000000000000214e8348c4f000000000000000000000000000000000000000000000000000000b1db941911680000000000000000000000000000000000000000000000000002c6c3c8a56068000"

**Comment by drlecks** [comment]
The problem is legit. 

For some unknown reason that I can't find documentation for, tuples including only static length parameters (address, bool, int...) are encoded without a head offset value. 

This issue affected requesting "static parameter structs" of tuples and arrays of "static parameter structs". I will discard this pull request as I commited a fix with this keeping compatibility with tuples containing dynamic parameters.


I've used attached contract + PHP code to test "static parameter structs". You can check `Example/example.call.php` for more complex tuple structures.

``` Solidity
// SPDX-License-Identifier: GPL-3.0

pragma solidity >=0.7.0 <0.9.0;
pragma abicoder v2; 

contract SWP_pull5
{ 
    struct Info1
    {
        uint256 elem1;
        uint256 elem2;
        uint256 elem3;
    }

    struct Info2
    {
        uint256 elem1;
        uint256 elem2;
        string text3;
    }

    struct Info3
    {
        address addr1;
        uint256 elem2;
        bool bool3;
    }
     
    Info1[] public infos1; 
    Info2[] public infos2;  
    Info3[] public infos3;    
     
    constructor() 
    {   
        Info1 memory i11 = Info1(1,2,3); 
        Info1 memory i12 = Info1(4,5,6); 
        Info1 memory i13 = Info1(7,8,9);   
        infos1.push(i11); 
        infos1.push(i12); 
        infos1.push(i13); 

        Info2 memory i21 = Info2(1,2,"aaa"); 
        Info2 memory i22 = Info2(4,5,"bbb"); 
        Info2 memory i23 = Info2(7,8,"ccc");   
        infos2.push(i21); 
        infos2.push(i22); 
        infos2.push(i23); 

        Info3 memory i31 = Info3(0xaAaAaAaaAaAaAaaAaAAAAAAAAaaaAaAaAaaAaaAa, 1, true); 
        Info3 memory i32 = Info3(0xbBbBBBBbbBBBbbbBbbBbbbbBBbBbbbbBbBbbBBbB, 2, true); 
        Info3 memory i33 = Info3(0xCcCCccccCCCCcCCCCCCcCcCccCcCCCcCcccccccC, 3, true);   
        infos3.push(i31); 
        infos3.push(i32); 
        infos3.push(i33); 
    }
   
    function GetInfo1_All() public view returns (Info1[] memory)
    {
        return infos1;
    } 

    function GetInfo1(uint256 index) public view returns (Info1 memory)
    {
        require (index < infos1.length);
        return infos1[index];
    }

    function GetInfo2(uint256 index) public view returns (Info2 memory)
    {
        require (index < infos2.length);
        return infos2[index];
    }

    function GetInfo3(uint256 index) public view returns (Info3 memory)
    {
        require (index < infos3.length);
        return infos3[index];
    } 
}
```

```PHP
<?php
/**
 * This file is part of simple-web3-php package.
 * 
 * (c) Alex Cabrera  
 * 
 * @author Alex Cabrera
 * @license MIT 
 */

namespace SWeb3;

ini_set('display_errors', '1');
ini_set('display_startup_errors', '1');

include_once("../vendor/autoload.php"); 
  
use SWeb3\SWeb3;
use SWeb3\SWeb3_Contract;
use phpseclib\Math\BigInteger as BigNumber;


//[INFURA START] DEFINE ONLY IF YOU ARE USING INFURA
//in case you are using infura, you can set these values (or *)
define('INFURA_PROJECT_ID', 'xxxxxxxxxxxxxxxxxxxxxxxxxxx');
define('INFURA_PROJECT_SECRET', 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx');
define('ETHEREUM_NET_NAME', 'ropsten'); //ropsten , mainnet
//[INFURA END]  

//REAL endpoint, this is what is really used internally
define('ETHEREUM_NET_ENDPOINT', 'https://'.ETHEREUM_NET_NAME.'.infura.io/v3/'.INFURA_PROJECT_ID); 

//SWP_pull5.sol is available on ropsten test net, address: 0x168e82547Eda9D42977f624b9CA9e17F9C677Ea4
define('SWP_Contract_Address','0x168e82547Eda9D42977f624b9CA9e17F9C677Ea4'); 
$SWP_Contract_ABI = '[{"inputs":[],"stateMutability":"nonpayable","type":"constructor"},{"inputs":[{"internalType":"uint256","name":"index","type":"uint256"}],"name":"GetInfo1","outputs":[{"components":[{"internalType":"uint256","name":"elem1","type":"uint256"},{"internalType":"uint256","name":"elem2","type":"uint256"},{"internalType":"uint256","name":"elem3","type":"uint256"}],"internalType":"struct SWP_pull5.Info1","name":"","type":"tuple"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"GetInfo1_All","outputs":[{"components":[{"internalType":"uint256","name":"elem1","type":"uint256"},{"internalType":"uint256","name":"elem2","type":"uint256"},{"internalType":"uint256","name":"elem3","type":"uint256"}],"internalType":"struct SWP_pull5.Info1[]","name":"","type":"tuple[]"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"index","type":"uint256"}],"name":"GetInfo2","outputs":[{"components":[{"internalType":"uint256","name":"elem1","type":"uint256"},{"internalType":"uint256","name":"elem2","type":"uint256"},{"internalType":"string","name":"text3","type":"string"}],"internalType":"struct SWP_pull5.Info2","name":"","type":"tuple"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"index","type":"uint256"}],"name":"GetInfo3","outputs":[{"components":[{"internalType":"address","name":"addr1","type":"address"},{"internalType":"uint256","name":"elem2","type":"uint256"},{"internalType":"bool","name":"bool3","type":"bool"}],"internalType":"struct SWP_pull5.Info3","name":"","type":"tuple"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"","type":"uint256"}],"name":"infos1","outputs":[{"internalType":"uint256","name":"elem1","type":"uint256"},{"internalType":"uint256","name":"elem2","type":"uint256"},{"internalType":"uint256","name":"elem3","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"","type":"uint256"}],"name":"infos2","outputs":[{"internalType":"uint256","name":"elem1","type":"uint256"},{"internalType":"uint256","name":"elem2","type":"uint256"},{"internalType":"string","name":"text3","type":"string"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"","type":"uint256"}],"name":"infos3","outputs":[{"internalType":"address","name":"addr1","type":"address"},{"internalType":"uint256","name":"elem2","type":"uint256"},{"internalType":"bool","name":"bool3","type":"bool"}],"stateMutability":"view","type":"function"}]';
define('SWP_Contract_ABI', $SWP_Contract_ABI);
 
 

//IMPORTANT
//Remember that this is an example showing how to reproduce pull request #5 
$extra_curl_params = [];
//INFURA ONLY: Prepare extra curl params, to add infura private key to the request
$extra_curl_params[CURLOPT_USERPWD] = ':'.INFURA_PROJECT_SECRET;

//initialize SWeb3 main object
$sweb3 = new SWeb3(ETHEREUM_NET_ENDPOINT, $extra_curl_params);
  

//CONTRACT 
//initialize contract from address and ABI string
$contract = new SWeb3_contract($sweb3, SWP_Contract_Address, SWP_Contract_ABI); 

//GETTERS - direct public variables     
$res = $contract->call('infos1', [1]);
PrintCallResult('infos1', $res); 

$res = $contract->call('GetInfo1_All');
PrintCallResult('GetInfo1_All', $res);  
 
$res = $contract->call('GetInfo1', [1]);
PrintCallResult('GetInfo1', $res);  
 
$res = $contract->call('GetInfo2', [1]);
PrintCallResult('GetInfo2', $res);  

$res = $contract->call('GetInfo3', [1]);
PrintCallResult('GetInfo3', $res);  
 
function PrintCallResult($callName, $result)
{
    echo "<br/> Call -> <b>". $callName . "</b><br/>";

    echo "Result -> " . PrintObject($result) . "<br/>"; 
}
 
function PrintObject($x)
{ 
	if ($x instanceof BigNumber)
	{
		return $x . '';
	}
	
	if (is_object($x)) {
		$x = (array)($x); 
	}

	if (is_array($x))
	{
		$text = "[";
		$first = true;
		foreach($x as $key => $value)
		{
			if ($first)  	$first = false;
			else 			$text .= ", ";

			$text .= $key . " : " . PrintObject($value);
		}

		return $text . "]"; 
	}
	 
	return $x . '';
}
```

**Pull request closed without merging**
